"""added new fields to the user model

Revision ID: 390bd453b77e
Revises: bd58d0d028a2
Create Date: 2018-07-25 22:09:47.647242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390bd453b77e'
down_revision = 'bd58d0d028a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
